[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.4.2",
    "faiss-cpu>=1.13.2",
    "httpx>=0.28.1",
    "numpy>=1.26,<2.3",
    "sentence-transformers>=5.2.0",
]
